### ISSUE TITLE
Infinite loop when checking algebra 2

### ISSUE THREAD

**Issue by HunterGiveMeSkymobile** [ImalolsLol/SkyMobile#1]
It gets stuck in "trying to get grades" when im trying to access 4th prd alg 2 grade

**Comment by HunterGiveMeSkymobile** [comment]
Final GPA not a number

**Comment by ImalolsLol** [comment]
Final GPA not a number is fixed, ill release sometime soon

**Comment by ImalolsLol** [comment]
New release will fix it

**Comment by lingfeishengtian** [comment]
Fixed in newest commit.
